[build]
  base = "/"
  publish = "dist"
  command = "npm run build"

# Proxy API requests to Railway backend
[[redirects]]
  from = "/api/*"
  to = "https://nodejs-production-0c33.up.railway.app/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Proxy ping requests to Railway backend
[[redirects]]
  from = "/ping"
  to = "https://nodejs-production-0c33.up.railway.app/ping"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Proxy cors-test requests to Railway backend
[[redirects]]
  from = "/cors-test"
  to = "https://nodejs-production-0c33.up.railway.app/cors-test"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Optimize asset caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache CSS, JS, and media files
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
